# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI-dev-pr

on:
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci

    - name: Update homepage in package.json
      run: |
          echo "Updating homepage to dev/pr"
          sed -i "s|\"homepage\": \".*\"|\"homepage\": \"https://maestrokd.github.io/gh-pages-demo/dev/pr\"|" package.json

    - run: npm run build --if-present
      env:
        REACT_APP_TEST_VAR: dev-pr
        REACT_APP_BE_REST_HOST: ${{ secrets.BE_REST_HOST_PR_DEV }}
    - run: npm test

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        destination_dir: 'dev/pr' # Subdirectory for development
