# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ci-main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci

    - name: Update homepage in package.json
      run: |
        echo "Updating homepage for prod"
        sed -i "s|\"homepage\": \".*\"|\"homepage\": \"https://maestrokd.github.io/gh-pages-demo/main\"|" package.json

    - run: npm run build --if-present
      env:
        REACT_APP_TEST_VAR: main
        REACT_APP_BE_REST_HOST: ${{ secrets.BE_REST_HOST_PROD }}
    - run: npm test

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        destination_dir: 'main' # Subdirectory for development

#    - name: Deploy with gh-pages
#      run: |
#        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
#        npm run deploy:prod -- -u "github-actions-bot <support+actions@github.com>"
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
